version: '3'

services:
  tss:
    container_name: tss
    image: golang:1.13
    working_dir: /home/user/tss
    command: bash /home/user/config/run.sh
    stdin_open: true
    tty: true
    ports:
      - 8320:8080
      - 8081:8081
    # logging:
    #   driver: none
    environment:
      - LOG=${LOG:-gaiad.log}
    volumes:
      - /home/ubuntu/go-tss/benchmark_docker/Data/data_local/:/home/user/config:Z
      - /home/ubuntu/go-tss/go-tss:/home/user/tss:z
    network_mode: "host"
